import 'server-only';
import { createAdminClient } from '@/lib/supabase/server';
import { requireEntitled } from '@/lib/auth';
import { enforceRateLimit } from '@/lib/rate-limit';

/**
 * Slip images and the "no sharing" rule.
 *
 * The `slips` bucket is private and members hold no storage grant, so an image
 * has no durable URL to copy. Every view mints a fresh signed URL, server-side,
 * only after the viewer's entitlement has been re-checked. A URL pasted into a
 * group chat stops working within SIGNED_URL_TTL_SECONDS.
 *
 * This raises the cost of leaking without pretending to eliminate it — a
 * screenshot is always possible. What it does prevent is the cheap failure:
 * a permanent CDN link circulating outside the paywall forever.
 */

export const SIGNED_URL_TTL_SECONDS = 90;

const BUCKET = 'slips';

/** Storage paths are generated by us; reject anything that could escape the prefix. */
const SAFE_PATH = /^[a-z0-9][a-z0-9/_-]{0,180}\.(png|jpe?g|webp)$/i;

export type SignedMedia = {
  id: string;
  url: string;
  width: number | null;
  height: number | null;
  expiresAt: string;
};

/**
 * Mints short-lived URLs for one post's media.
 *
 * Entitlement is checked here rather than trusted from the caller, so this is
 * safe to expose behind a route handler. It returns an empty array rather than
 * throwing when a post has no media.
 */
export async function signPostMedia(postId: string): Promise<SignedMedia[]> {
  const { user } = await requireEntitled();
  await enforceRateLimit('media', user.id);

  const admin = createAdminClient();

  // Re-ask the database whether this user may read this post, rather than
  // assuming that holding an entitlement is enough — the post may be gated to
  // a longer plan than the caller holds.
  const { data: readable, error: readErr } = await admin.rpc('can_read_post_for', {
    p_post_id: postId,
    p_user_id: user.id,
  });

  if (readErr || readable !== true) return [];

  const { data: media, error } = await admin
    .from('post_media')
    .select('id, storage_path, width, height')
    .eq('post_id', postId);

  if (error || !media?.length) return [];

  const expiresAt = new Date(Date.now() + SIGNED_URL_TTL_SECONDS * 1000).toISOString();
  const signed: SignedMedia[] = [];

  for (const row of media) {
    if (!SAFE_PATH.test(row.storage_path)) {
      console.error('[media] refusing to sign suspicious path', row.storage_path);
      continue;
    }

    const { data: url, error: signErr } = await admin.storage
      .from(BUCKET)
      .createSignedUrl(row.storage_path, SIGNED_URL_TTL_SECONDS);

    if (signErr || !url) continue;

    signed.push({
      id: row.id,
      url: url.signedUrl,
      width: row.width,
      height: row.height,
      expiresAt,
    });
  }

  return signed;
}

/** Builds the storage path for a new upload. Never derived from user input. */
export function buildStoragePath(postId: string, extension: 'png' | 'jpg' | 'webp'): string {
  const stamp = Date.now().toString(36);
  const nonce = crypto.randomUUID().slice(0, 8);
  return `posts/${postId}/${stamp}-${nonce}.${extension}`;
}

/**
 * Batch variant for the feed.
 *
 * Signing each post separately would spend one rate-limit token per card and
 * fire N round-trips to build one screen. This takes a single token, resolves
 * visibility for the whole set in one query, and signs in parallel.
 *
 * Entitlement is still enforced: `post_media` rows are fetched with the
 * SESSION-scoped client, so row level security drops anything the caller may
 * not read before a URL is ever minted.
 */
export async function signMediaForPosts(
  postIds: string[],
): Promise<Map<string, SignedMedia[]>> {
  const out = new Map<string, SignedMedia[]>();
  if (postIds.length === 0) return out;

  const { user } = await requireEntitled();
  await enforceRateLimit('media', user.id);

  const { createClient } = await import('@/lib/supabase/server');
  const scoped = await createClient();

  const { data: media, error } = await scoped
    .from('post_media')
    .select('id, post_id, storage_path, width, height')
    .in('post_id', postIds);

  if (error || !media?.length) return out;

  const admin = createAdminClient();
  const expiresAt = new Date(Date.now() + SIGNED_URL_TTL_SECONDS * 1000).toISOString();

  const usable = media.filter((row) => {
    const ok = SAFE_PATH.test(row.storage_path);
    if (!ok) console.error('[media] refusing to sign suspicious path', row.storage_path);
    return ok;
  });

  const signed = await Promise.all(
    usable.map(async (row) => {
      const { data, error: signErr } = await admin.storage
        .from(BUCKET)
        .createSignedUrl(row.storage_path, SIGNED_URL_TTL_SECONDS);
      if (signErr || !data) return null;
      return {
        postId: row.post_id,
        media: { id: row.id, url: data.signedUrl, width: row.width, height: row.height, expiresAt },
      };
    }),
  );

  for (const entry of signed) {
    if (!entry) continue;
    const list = out.get(entry.postId) ?? [];
    list.push(entry.media);
    out.set(entry.postId, list);
  }

  return out;
}
